// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCXFNFn_jb_puZWKj0ODtCG6rY28jBZ-M',
    appId: '1:430999021506:web:112351bc65994d1178185b',
    messagingSenderId: '430999021506',
    projectId: 'todo-list-app-35513',
    authDomain: 'todo-list-app-35513.firebaseapp.com',
    storageBucket: 'todo-list-app-35513.firebasestorage.app',
    measurementId: 'G-T6GVZ13LGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXMVXF6HSuRuYzNvTgv_gxea99M70hMBg',
    appId: '1:430999021506:android:8885dfdd5f58fce378185b',
    messagingSenderId: '430999021506',
    projectId: 'todo-list-app-35513',
    storageBucket: 'todo-list-app-35513.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb5kVR2bkUVtyUGFK3XZtod3OCISQJGr0',
    appId: '1:430999021506:ios:0a59ce966806c73a78185b',
    messagingSenderId: '430999021506',
    projectId: 'todo-list-app-35513',
    storageBucket: 'todo-list-app-35513.firebasestorage.app',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb5kVR2bkUVtyUGFK3XZtod3OCISQJGr0',
    appId: '1:430999021506:ios:0a59ce966806c73a78185b',
    messagingSenderId: '430999021506',
    projectId: 'todo-list-app-35513',
    storageBucket: 'todo-list-app-35513.firebasestorage.app',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCXFNFn_jb_puZWKj0ODtCG6rY28jBZ-M',
    appId: '1:430999021506:web:2f322f46b171fa6478185b',
    messagingSenderId: '430999021506',
    projectId: 'todo-list-app-35513',
    authDomain: 'todo-list-app-35513.firebaseapp.com',
    storageBucket: 'todo-list-app-35513.firebasestorage.app',
    measurementId: 'G-PHD7P9Z172',
  );
}
