// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSk3Av39Ma9Xu2MVWVUIzxyaAMR8qu3JA',
    appId: '1:957835090640:web:d70f67d5ae75b6d6ba5cd5',
    messagingSenderId: '957835090640',
    projectId: 'shopping-cart-4a481',
    authDomain: 'shopping-cart-4a481.firebaseapp.com',
    storageBucket: 'shopping-cart-4a481.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhcSUF4-zlTm8cexnxQeqJVGnqSQIgEj0',
    appId: '1:957835090640:android:9bac5e84a87c535eba5cd5',
    messagingSenderId: '957835090640',
    projectId: 'shopping-cart-4a481',
    storageBucket: 'shopping-cart-4a481.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzO9H53C3W049cfblSmyAYuBnjSDi0ipU',
    appId: '1:957835090640:ios:9922d3f7be9402b0ba5cd5',
    messagingSenderId: '957835090640',
    projectId: 'shopping-cart-4a481',
    storageBucket: 'shopping-cart-4a481.firebasestorage.app',
    iosBundleId: 'com.example.shoppingCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzO9H53C3W049cfblSmyAYuBnjSDi0ipU',
    appId: '1:957835090640:ios:9922d3f7be9402b0ba5cd5',
    messagingSenderId: '957835090640',
    projectId: 'shopping-cart-4a481',
    storageBucket: 'shopping-cart-4a481.firebasestorage.app',
    iosBundleId: 'com.example.shoppingCart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSk3Av39Ma9Xu2MVWVUIzxyaAMR8qu3JA',
    appId: '1:957835090640:web:151b3c60d4c4ff6fba5cd5',
    messagingSenderId: '957835090640',
    projectId: 'shopping-cart-4a481',
    authDomain: 'shopping-cart-4a481.firebaseapp.com',
    storageBucket: 'shopping-cart-4a481.firebasestorage.app',
  );

}